# application.properties
# Spring Boot ?????? application.yml ???properties ???????
# ???????????????????????????

spring.application.name=ComputerAssociation

logging.file.path=logs

logging.level.root=INFO
logging.level.com.example.computerassociation=DEBUG
logging.level.org.springframework=INFO
logging.level.org.springframework.security=INFO
logging.level.org.apache.ibatis=INFO